// AUTO-GENERATED by scripts/generate-migrations-manifest.ts — do not hand-edit.
// Regenerate with `npm run generate-migrations` after adding a migration.
//
// Embeds every migration file's SQL as a literal string constant, so
// Next.js's file tracer (@vercel/nft) has no path resolution to get wrong:
// this is a normal JS module, guaranteed to be included in any bundle that
// imports it, the same as any other application code. See migrate.ts for
// why a runtime fs read — even with a fully static literal path — was not
// good enough; that was the real failure mode found on the first live
// Vercel deploy against Supabase.
export interface MigrationSource {
  id: string;
  postgres: string;
  sqlite: string;
}

export const MIGRATIONS: MigrationSource[] = [
  {
    id: "001-init",
    postgres: `-- Plan 02: project config storage. Traffic (plan 04) and counter (plan 10)
-- tables arrive in their own numbered migrations when those plans are built.
create table project (
  slug            text primary key,
  workspace_id    text        not null default 'default',
  name            text        not null,
  base_path       text,
  defaults        jsonb       not null,
  openapi_doc     jsonb,
  source          text        not null default 'store',
  config_version  bigint      not null default 1,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table rule (
  id           bigserial primary key,
  slug         text   not null references project(slug) on delete cascade,
  rule_id      text   not null,
  position     int    not null,
  definition   jsonb  not null,
  created_at   timestamptz not null default now(),
  unique (slug, rule_id)
);
create index rule_slug_position_idx on rule (slug, position);
`,
    sqlite: `-- Same two tables as 001-init.postgres.sql, translated to SQLite:
-- jsonb -> text (JSON.stringify'd, parsed back by the driver), bigserial ->
-- integer primary key autoincrement, timestamptz -> text ISO-8601.
create table project (
  slug            text primary key,
  workspace_id    text not null default 'default',
  name            text not null,
  base_path       text,
  defaults        text not null,
  openapi_doc     text,
  source          text not null default 'store',
  config_version  integer not null default 1,
  created_at      text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at      text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

create table rule (
  id           integer primary key autoincrement,
  slug         text not null references project(slug) on delete cascade,
  rule_id      text not null,
  position     integer not null,
  definition   text not null,
  created_at   text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  unique (slug, rule_id)
);
create index rule_slug_position_idx on rule (slug, position);
`,
  },
  {
    id: "002-traffic",
    postgres: `-- Plan 04: traffic recording. Redaction happens before a row ever reaches
-- this table (src/store/redact.ts) — nothing here re-redacts on read.
create table traffic (
  id uuid primary key,
  slug text not null,
  at timestamptz not null default now(),
  method text not null,
  path text not null,
  query jsonb not null default '{}',
  req_headers jsonb not null default '{}',
  req_body text,
  status int not null,
  res_headers jsonb not null default '{}',
  res_body text,
  matched_rule_id text,
  duration_ms int not null,
  warnings jsonb not null default '[]',
  client_hash text,
  config_version bigint,
  truncated boolean not null default false
);
create index traffic_slug_at_idx on traffic (slug, at desc);
create index traffic_slug_rule_at_idx on traffic (slug, matched_rule_id, at desc);
-- Unmatched-inbox (plan 05): instant regardless of total volume.
create index traffic_slug_unmatched_idx on traffic (slug, at desc) where matched_rule_id is null;
`,
    sqlite: `-- Same table as 002-traffic.postgres.sql. jsonb -> text (JSON.stringify'd),
-- timestamptz -> text ISO-8601, uuid -> text. SQLite supports partial indexes
-- (3.8.0+), so the unmatched-inbox index below is not a Postgres-only trick.
create table traffic (
  id text primary key,
  slug text not null,
  at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  method text not null,
  path text not null,
  query text not null default '{}',
  req_headers text not null default '{}',
  req_body text,
  status integer not null,
  res_headers text not null default '{}',
  res_body text,
  matched_rule_id text,
  duration_ms integer not null,
  warnings text not null default '[]',
  client_hash text,
  config_version integer,
  truncated integer not null default 0
);
create index traffic_slug_at_idx on traffic (slug, at desc);
create index traffic_slug_rule_at_idx on traffic (slug, matched_rule_id, at desc);
create index traffic_slug_unmatched_idx on traffic (slug, at desc) where matched_rule_id is null;
`,
  },
  {
    id: "003-upstream",
    postgres: `-- Plan 07: proxy & record from upstream. Additive only — old code that never
-- reads \`project.upstream\` or \`traffic.via_upstream\` keeps working unchanged.
alter table project add column upstream jsonb;
alter table traffic add column via_upstream boolean not null default false;
`,
    sqlite: `-- Same as 003-upstream.postgres.sql. jsonb -> text (JSON.stringify'd), boolean
-- -> integer 0/1. Additive only.
alter table project add column upstream text;
alter table traffic add column via_upstream integer not null default 0;
`,
  },
  {
    id: "004-counter",
    postgres: `-- Plan 10: per-(slug, rule, session) call counters for stateful variant rules.
-- Additive; a non-variant rule never touches this table.
create table counter (
  slug       text        not null,
  rule_id    text        not null,
  session    text        not null,
  n          bigint      not null default 0,
  updated_at timestamptz not null default now(),
  primary key (slug, rule_id, session)
);
create index counter_updated_at_idx on counter (updated_at);
`,
    sqlite: `-- Same as 004-counter.postgres.sql. bigint -> integer, timestamptz -> text ISO-8601.
create table counter (
  slug       text    not null,
  rule_id    text    not null,
  session    text    not null,
  n          integer not null default 0,
  updated_at text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  primary key (slug, rule_id, session)
);
create index counter_updated_at_idx on counter (updated_at);
`,
  },
  {
    id: "005-faults",
    postgres: `-- Plan 11: fault injection config. Additive; a project without a \`faults\`
-- block behaves exactly as before.
alter table project add column faults jsonb;
`,
    sqlite: `-- Same as 005-faults.postgres.sql. jsonb -> text (JSON.stringify'd).
alter table project add column faults text;
`,
  },
  {
    id: "006-callback-direction",
    postgres: `-- Plan 12: outbound callback deliveries are recorded as traffic rows too,
-- distinguished by direction. Additive; existing rows default to 'inbound'.
alter table traffic add column direction text not null default 'inbound';
`,
    sqlite: `-- Same as 006-callback-direction.postgres.sql.
alter table traffic add column direction text not null default 'inbound';
`,
  },
  {
    id: "007-variables",
    postgres: `-- Plan 17: project variables + the default environment name. Additive.
alter table project add column variables jsonb;
alter table project add column default_environment text;
`,
    sqlite: `-- Same as 007-variables.postgres.sql. jsonb -> text.
alter table project add column variables text;
alter table project add column default_environment text;
`,
  },
  {
    id: "008-contract",
    postgres: `-- Plan 13: contract validation config. Additive.
alter table project add column contract jsonb;
`,
    sqlite: `-- Same as 008-contract.postgres.sql. jsonb -> text.
alter table project add column contract text;
`,
  },
  {
    id: "009-config-event",
    postgres: `-- Plan 15: append-only config history. Written in the same transaction as the
-- change it records — a change with no event is a change nobody can undo.
create table config_event (
  id        bigserial   primary key,
  slug      text        not null,
  at        timestamptz not null default now(),
  actor     text,                       -- user id, token name, or 'repo-sync'
  kind      text        not null,       -- project.update | rule.create | rule.update
                                        -- | rule.delete | rule.reorder | import | revert
  target_id text,                       -- rule id, where applicable
  before    jsonb,                      -- null on create
  after     jsonb,                      -- null on delete
  version   bigint      not null        -- config_version after this event
);
create index config_event_slug_at_idx on config_event (slug, at desc);
`,
    sqlite: `-- Same as 009-config-event.postgres.sql. bigserial -> integer autoincrement,
-- timestamptz -> text ISO-8601, jsonb -> text.
create table config_event (
  id         integer primary key autoincrement,
  slug       text    not null,
  at         text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  actor      text,
  kind       text    not null,
  target_id  text,
  before     text,
  after      text,
  version    integer not null
);
create index config_event_slug_at_idx on config_event (slug, at desc);
`,
  },
  {
    id: "010-flows",
    postgres: `-- Plan 16: flows — a saved, runnable sequence of requests with assertions.
create table flow (
  id          text        not null,
  slug        text        not null,
  name        text        not null,
  definition  jsonb       not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (slug, id)
);

create table flow_run (
  id          uuid        primary key,
  slug        text        not null,
  flow_id     text        not null,
  started_at  timestamptz not null default now(),
  finished_at timestamptz,
  status      text        not null,       -- running | passed | failed | error
  results     jsonb       not null default '[]'
);
create index flow_run_slug_flow_started_idx on flow_run (slug, flow_id, started_at desc);
`,
    sqlite: `-- Same as 010-flows.postgres.sql. jsonb -> text, timestamptz -> text ISO-8601,
-- uuid -> text.
create table flow (
  id          text not null,
  slug        text not null,
  name        text not null,
  definition  text not null,
  created_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at  text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  primary key (slug, id)
);

create table flow_run (
  id          text    primary key,
  slug        text    not null,
  flow_id     text    not null,
  started_at  text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  finished_at text,
  status      text    not null,
  results     text    not null default '[]'
);
create index flow_run_slug_flow_started_idx on flow_run (slug, flow_id, started_at desc);
`,
  },
  {
    id: "011-docs",
    postgres: `-- Plan 18: the public docs portal config. Additive; off by default.
alter table project add column docs jsonb;
`,
    sqlite: `-- Same as 011-docs.postgres.sql. jsonb -> text.
alter table project add column docs text;
`,
  },
  {
    id: "012-views-and-alerts",
    postgres: `-- Plan 21: saved views (a name + a traffic filter) and alerts (a view + a
-- threshold + a destination). Alerts carry their own evaluation state
-- (last fired/recovered/error, currently firing) so the cron sweep and the
-- Test button both read and write through one row, never two sources of truth.
create table saved_view (
  id         text        not null,
  slug       text        not null,
  name       text        not null,
  query      jsonb       not null,
  created_at timestamptz not null default now(),
  primary key (slug, id)
);

create table alert (
  id                 text        not null,
  slug               text        not null,
  name               text        not null,
  view               text        not null,
  condition          jsonb       not null,
  notify             jsonb       not null,
  cooldown_minutes   int         not null default 30,
  enabled            boolean     not null default true,
  last_fired_at      timestamptz,
  last_recovered_at  timestamptz,
  last_error         text,
  currently_firing   boolean     not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  primary key (slug, id)
);
create index alert_enabled_idx on alert (enabled) where enabled;
`,
    sqlite: `-- Same as 012-views-and-alerts.postgres.sql. jsonb -> text, boolean -> integer,
-- timestamptz -> text ISO-8601.
create table saved_view (
  id         text not null,
  slug       text not null,
  name       text not null,
  query      text not null,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  primary key (slug, id)
);

create table alert (
  id                text    not null,
  slug              text    not null,
  name              text    not null,
  view              text    not null,
  condition         text    not null,
  notify            text    not null,
  cooldown_minutes  integer not null default 30,
  enabled           integer not null default 1,
  last_fired_at     text,
  last_recovered_at text,
  last_error        text,
  currently_firing  integer not null default 0,
  created_at        text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at        text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  primary key (slug, id)
);
create index alert_enabled_idx on alert (enabled);
`,
  },
  {
    id: "013-drift",
    postgres: `-- Plan 22: drift detection config (on project) and current drift state (one
-- row per rule, upserted by each check; a rule with no drift has no row).
alter table project add column drift jsonb;

create table drift_report (
  id               text        not null, -- == rule_id, or "__openapi_spec__"
  slug             text        not null,
  rule_id          text        not null,
  findings         jsonb       not null default '[]',
  observed_response jsonb,
  error            text,
  dismissed        boolean     not null default false,
  first_seen_at    timestamptz not null default now(),
  last_checked_at  timestamptz not null default now(),
  primary key (slug, id)
);
`,
    sqlite: `-- Same as 013-drift.postgres.sql. jsonb -> text, boolean -> integer,
-- timestamptz -> text ISO-8601.
alter table project add column drift text;

create table drift_report (
  id               text    not null,
  slug             text    not null,
  rule_id          text    not null,
  findings         text    not null default '[]',
  observed_response text,
  error            text,
  dismissed        integer not null default 0,
  first_seen_at    text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  last_checked_at  text    not null default (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  primary key (slug, id)
);
`,
  },
];
