import { describe, it, expect } from "vitest";
import { ruleSchema } from "../compile/schema";
import { synthesizeRequest } from "../viewer/curl";
import { parseCurl, shellSplit } from "./curl-parse";

function drafts(r: ReturnType<typeof parseCurl>) {
  if ("error" in r) throw new Error(r.error);
  return r;
}

describe("shellSplit", () => {
  it("keeps single-quoted spans intact", () => {
    expect(shellSplit("curl -H 'Content-Type: application/json' https://x")).toEqual([
      "curl",
      "-H",
      "Content-Type: application/json",
      "https://x",
    ]);
  });
  it("follows backslash-newline continuations", () => {
    expect(shellSplit("curl \\\n  -X POST \\\n  https://x")).toEqual(["curl", "-X", "POST", "https://x"]);
  });
});

describe("parseCurl", () => {
  it("turns a GET with query params into a rule with query match conditions", () => {
    const { drafts: [d], unsupported } = drafts(parseCurl("curl 'https://api.example.com/search?q=cats&page=2'"));
    expect(d!.rule.request.method).toBe("GET");
    expect(d!.rule.request.path).toBe("/search");
    expect(d!.rule.request.match).toEqual([
      { query: "q", equals: "cats" },
      { query: "page", equals: "2" },
    ]);
    expect(ruleSchema.safeParse(d!.rule).success).toBe(true);
    expect(unsupported).toEqual([]);
  });

  it("turns a POST JSON body into top-level jsonPath match conditions", () => {
    const { drafts: [d] } = drafts(
      parseCurl(`curl -X POST https://api.example.com/users -H 'content-type: application/json' -d '{"name":"Ada","age":36,"admin":true}'`),
    );
    expect(d!.rule.request.method).toBe("POST");
    expect(d!.rule.request.match).toEqual([
      { jsonPath: "$.name", equals: "Ada" },
      { jsonPath: "$.age", equals: "36" },
      { jsonPath: "$.admin", equals: "true" },
    ]);
  });

  it("defaults to POST when there is a body and no -X", () => {
    const { drafts: [d] } = drafts(parseCurl(`curl https://x/a -d '{"k":1}'`));
    expect(d!.rule.request.method).toBe("POST");
  });

  it("reports an unrecognised flag instead of dropping it", () => {
    const { unsupported } = drafts(parseCurl("curl --http2 https://x/a"));
    expect(unsupported.some((u) => u.includes("--http2"))).toBe(true);
  });

  it("notes a non-JSON body rather than failing", () => {
    const { drafts: [d], unsupported } = drafts(parseCurl("curl -X POST https://x/a -d 'name=Ada&age=36'"));
    expect(d!.rule.request.match).toBeUndefined();
    expect(unsupported.some((u) => u.includes("not JSON"))).toBe(true);
  });

  it("errors on a command with no URL", () => {
    const r = parseCurl("curl -X GET -H 'a: b'");
    expect("error" in r && r.error).toMatch(/no URL/);
  });

  it("round-trips a command generated by src/viewer/curl.ts to an equivalent rule", () => {
    const gen = synthesizeRequest({
      method: "POST",
      runUrl: "/orders/create",
      match: [
        { jsonPath: "$.sku", equals: "ABC-1" },
        { header: "x-env", equals: "qa" },
        { query: "dry", equals: "1" },
      ],
    });
    const { drafts: [d] } = drafts(parseCurl(gen.curl));
    expect(d!.rule.request.method).toBe("POST");
    expect(d!.rule.request.path).toBe("/orders/create");
    // query + body conditions survive the round trip (headers are noted, not matched)
    expect(d!.rule.request.match).toEqual(
      expect.arrayContaining([
        { query: "dry", equals: "1" },
        { jsonPath: "$.sku", equals: "ABC-1" },
      ]),
    );
    expect(ruleSchema.safeParse(d!.rule).success).toBe(true);
  });
});
