// Plan 24 — regenerates src/store/migrations-manifest.ts from the raw .sql
// files under src/store/migrations/. Run this whenever a migration is
// added: `npm run generate-migrations`.
//
// Why this exists instead of reading the .sql files at runtime: Next.js's
// file tracer (@vercel/nft) couldn't see them no matter how the read was
// shaped (a readdirSync() scan, or even readFileSync() with a fully
// resolvable literal path) — the first real Vercel deploy against Supabase
// failed with ENOENT on every migration file. Embedding the SQL as string
// constants in a real TS module sidesteps file tracing entirely: it's
// ordinary application code, bundled the same way any other import is.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationsDir = join(__dirname, "..", "src", "store", "migrations");
const outFile = join(__dirname, "..", "src", "store", "migrations-manifest.ts");

function ids(): string[] {
  const files = readdirSync(migrationsDir);
  const found = new Set<string>();
  for (const f of files) {
    const m = /^(.+)\.(postgres|sqlite)\.sql$/.exec(f);
    if (m) found.add(m[1]!);
  }
  return [...found].sort();
}

function escape(sql: string): string {
  return sql.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const allIds = ids();
let out = `// AUTO-GENERATED by scripts/generate-migrations-manifest.ts — do not hand-edit.
// Regenerate with \`npm run generate-migrations\` after adding a migration.
//
// Embeds every migration file's SQL as a literal string constant, so
// Next.js's file tracer (@vercel/nft) has no path resolution to get wrong:
// this is a normal JS module, guaranteed to be included in any bundle that
// imports it, the same as any other application code. See migrate.ts for
// why a runtime fs read — even with a fully static literal path — was not
// good enough; that was the real failure mode found on the first live
// Vercel deploy against Supabase.
export interface MigrationSource {
  id: string;
  postgres: string;
  sqlite: string;
}

export const MIGRATIONS: MigrationSource[] = [
`;

for (const id of allIds) {
  const pg = readFileSync(join(migrationsDir, `${id}.postgres.sql`), "utf8");
  const sq = readFileSync(join(migrationsDir, `${id}.sqlite.sql`), "utf8");
  out += `  {\n    id: ${JSON.stringify(id)},\n    postgres: \`${escape(pg)}\`,\n    sqlite: \`${escape(sq)}\`,\n  },\n`;
}
out += "];\n";

writeFileSync(outFile, out);
console.log(`[generate-migrations] wrote ${allIds.length} migration(s) to ${outFile}`);
